driver:
  controllerType: Xbox
  rumble: true
  joysticks:
    left:
      horizontal: strafe
      vertical: throttle
    right:
      horizontal: rotation
  buttonpad:
    b: brakeMode
    x:
    a:
    y:
  axes:
    rightTrigger: turboMode
    leftTrigger: slowMode
  buttons:
    start: zeroPose
    back: hardZeroPose
    leftBumper:
    rightBumper:
  dpad:
    up:
    down:
    left:
    right:
operator:
  controllerType: Xbox
  rumble: true
  buttonpad:
    y:
buttonboard:
  upLeft:
  upRight:
  up:
  center:
  left:
  downLeft:
  down:
demoMode: false