driver:
  controllerType: Xbox
  rumble: true
  joysticks:
    left:
      horizontal: strafe
      vertical: throttle
    right:
      horizontal: rotation
  buttonpad:
    a: activationDeepHanger
    b: intake/OuttakeAlgae
    x: outtakeCoral
    y:
  axes:
    rightTrigger: pivotA1/L3
    leftTrigger: pivotA2/L4
  buttons:
    start:
    back: zeroPose
    leftBumper: pivotElevatorAndCoralL2
    rightBumper: pivotElevatorAndCoralL1
  dpad:
    up:
    down:
    left:
    right:
operator:
  controllerType: Xbox
  rumble: true
  buttonpad:
    y:
buttonboard:
  upLeft:
  upRight: decreaseCoralArmPivotOffset
  up: increaseElevatorPivotOffset
  center: decreaseElevatorPivotOffset
  left:
  right: increaseCoralArmPivotOffset
  downLeft:
  down:
demoMode: false