driver:
  controllerType: Xbox
  rumble: true
  joysticks:
    left:
      horizontal: strafe
      vertical: throttle
    right:
      horizontal: rotation
  buttonpad:
    a: activationDeepHanger
    b: feeder
    x: outtakeCoral
    y: removeAlgae
  axes:
    rightTrigger: L3
    leftTrigger: L4
  buttons:
    start:
    back: zeroPose
    leftBumper: L2
    rightBumper: L1
  dpad:
    right: robotcentricRight
    down: robotcentricDown
    left: robotcentricLeft
    up: robotcentricUp
operator:
  controllerType: Xbox
  rumble: true
  buttonpad:
    y:
buttonboard:
  upLeft: increaseAlgaePivotOffset
  upRight: decreaseCoralArmPivotOffset
  up: increaseElevatorPivotOffset
  center: decreaseElevatorPivotOffset
  left: decreaseAlgaePivotOffset
  right: increaseCoralArmPivotOffset
  downLeft:
  down:
demoMode: false