driver:
  controllerType: Xbox
  rumble: true
  joysticks:
    left:
      horizontal: strafe
      vertical: throttle
    right:
      horizontal: rotation
  buttonpad:
    a: freedomPathingSpeaker
    b: freedomPathingSpeaker
    x:
    y:
  axes:
    rightTrigger:
    leftTrigger:
  buttons:
    start: zeroPose
    back: hardZeroPose
    leftBumper:
    rightBumper: 
  dpad:
    up:
    down:
    left:
    right:
operator:
  controllerType: Xbox
  rumble: true
  buttonpad:
    y:
buttonboard:
  upLeft: increaseAlgaePivotOffset
  upRight: decreaseCoralArmPivotOffset
  up: increaseElevatorPivotOffset
  center: decreaseElevatorPivotOffset
  left: decreaseAlgaePivotOffset
  right: increaseCoralArmPivotOffset
  downLeft:
  down:
demoMode: false