# TODO: Will need to be updated once "REEFSCAPE" robot, Zone is present. Currently, is not accurate
subsystems:
    drivetrain:
        implemented: true
        motors:
            rightMain:
                motorType: TalonFX
                motorName: rightMain
                id: 2
                invertMotor: false
            leftMain:
                motorType: TalonFX
                motorName: leftMain
                id: 1
                invertMotor: false
        pidConfig:
            slot0:
                kP: 0.1 # 0.18
                kI: 0.0001 # 0.018
                kD: 4.0 # 3.6
                kF: 0.0475813
        constants:
            ## Positional Configurations ##
            openLoopRampRate: 0.1
            isSwerve: 0
            isCTRSwerve: 0 #TODO IF ALL ELSE FAILS
            wheelDiameter: 3.81 #inches
            kTrackScrubFactor: 1.0
            ## Velocity Constraints ##
            maxRotVel: 0.8 # Pi radians/sec
            maxRotVelClosedLoop: 2 # Pi radians/sec
            trackWidth: 22.75 # inches
            wheelbaseLength: 22.75 # inches
            maxVelOpenLoop: 3 # meters/s
            maxVel12VMPS: 5.2
            maxVelPathFollowing: 4 # meters/s
            maxAccel: 2 # meters/s^2
            isDemoMode: 0
            ## Swerve Characterization ##
            driveGearRatio: 6.75 # L2
            azimuthGearRatio: 12.8 # MK4
            azimuthEncPPR: 0
            ## Control Configurations ##
            slowModeScalar: 0.4
            turboModeScalar: 1.73
            driveDeadband: 0.1
            rotationalDeadband: 0.1
            inputDeadband: 0.15 # Deadband of the normalized input
            snapDivisor: 30
    camera:
        implemented: false
        constants:
            useMultiTargetOdometry: 0
infrastructure:
    canBusName: highspeed
    ## Power Distribution ##
    pdId: 1
    pdIsRev: true
    ## Pneumatics Control ##
    compressorEnabled: false
    pcmIsRev: false
    pcmId: -1
    ## Pigeon ##
    pigeonId: 5
    isPigeon2: true
inputHandler: drivercentric # the default input handler
constants:
    zeroingButton: 9 # channel of DIO port
    enableMusic: 0
    ## Drivetrain ##
    minAllowablePoseError: 0.025
    maxAllowablePoseError: 5
    soundOnConfig: 0 #If this is false, It will still beep on robot bootup.
    rotationToleranceClosedLoop: 0.5
    ## Logging ##
    logRobot: 1 # 0 or 1
    logDrivetrain: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    ## General ##
    usingVision: 0
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .025 # seconds
    isProLicensed: 0
    hasCanivore: 1 # 0 or 1
    resetFactoryDefaults: 0 # whether motors get reset to factory default