subsystems:
    drivetrain:
        implemented: false
        motors:
            RRDr:
                motorType: TalonFX
                motorName: BRDr
                id: 0
                invertMotor: false
            RRAz:
                motorType: TalonFX
                motorName: BRAz
                id: 1
                invertMotor: false
            FRDr:
                motorType: TalonFX
                motorName: FRDr
                id: 3
                invertMotor: false
            FRAz:
                motorType: TalonFX
                motorName: FRAz
                id: 4
                invertMotor: false
            FLDr:
                motorType: TalonFX
                motorName: FLDr
                id: 6
                invertMotor: false
            FLAz:
                motorType: TalonFX
                motorName: FLAz
                id: 7
                invertMotor: false
            RLDr:
                motorType: TalonFX
                motorName: BLDr
                id: 9
                invertMotor: false
            RLAz:
                motorType: TalonFX
                motorName: BLAz
                id: 10
                invertMotor: false
        canCoders:
            RREnc: 2
            FREnc: 5
            FLEnc: 8
            RLEnc: 11
        swerveModules:
            modules:
                backRight:
                    drive: RRDr
                    azimuth: RRAz
                    canCoder: RREnc
                    xCoord: -11.875
                    yCoord: -11.875
                    constants:
                        encoderOffset: 0.3076171875
                        couplingRatio: 3.589
                        freeSpin12VRPS: 104
                        invertSensorPhase: 1
                frontRight:
                    drive: FRDr
                    azimuth: FRAz
                    canCoder: FREnc
                    xCoord: 11.875
                    yCoord: -11.875
                    constants:
                        encoderOffset: 0.014404296875
                        couplingRatio: 3.579
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                frontLeft:
                    drive: FLDr
                    azimuth: FLAz
                    canCoder: FLEnc
                    xCoord: 11.875
                    yCoord: 11.875
                    constants:
                        encoderOffset: 0.34228515625
                        couplingRatio: 3.576
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                backLeft:
                    drive: RLDr
                    azimuth: RLAz
                    canCoder: RLEnc
                    xCoord: -11.875
                    yCoord: 11.875
                    constants:
                        encoderOffset: 0.23779296875
                        couplingRatio: 3.572
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
            drivePID:
                slot0:
                    kP: 0.1
                    kI: 0.0005
                    kD: 0.0015
                    kV: 0.115
                    kS: 0
                    kA: 0
                    kG: 0
            azimuthPID:
                slot0:
                    kP: 50
                    kI: 0
                    kD: 0.5
                    kV: 2.66
                    kS: 0.1
                    kA: 0
                    kG: 0

        constants:
            ## Positional Configurations ##
            openLoopRampRate: 0.1
            isSwerve: 1
            isCTRSwerve: 1 #TODO IF ALL ELSE FAILS
            ## Velocity Constraints ##
            maxRotVel: 0.8 # Pi radians/sec
            maxRotVelClosedLoop: 2 # Pi radians/sec
            wheelDiameter: 4
            trackWidth: 22.75 # inches
            wheelbaseLength: 22.75 # inches
            maxVelOpenLoop: 3 # meters/s
            maxVelPathFollowing: 1 # meters/s
            maxAccel: 1 # meters/s^2
            #FR OUT, RL OUT, FL IN, BR IN
            isDemoMode: 0
            ## Swerve Characterization ##
            azimuthEncPPR: 2048
            ## Control Configurations ##
            slowModeScalar: 0.4
            turboModeScalar: 1.73
            driveDeadband: 0.1
            rotationalDeadband: 0.1
            inputDeadband: 0.15 # Deadband of the normalized input
            snapDivisor: 30
    coralArm:
        implemented: false
        motors:
            coralArmIntakeMotor:
                motorType: SparkMax
                motorName: coralArmIntakeMotor
                id: 12
                invertMotor: false
                currentLimit: 25
            coralArmPivotMotor:
                motorType: TalonFX
                motorName: coralArmPivotMotor
                id: 13
                invertMotor: true
                currentLimit: 20
                isLowSpeedCanBus: true
                motionMagic:
                    expoKV: 0.12
                    expoKA: 0.1
        pidConfig:
            slot0: #Pivot
                kP: 0.05
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            intakeSpeed: -.80
            outtakeSpeed: .80
            holdSpeed: 0
            removeAlgaeSpeed: -.80

            coralSensorChannel: 9

            coralArmL1Position: 36
            coralArmL2CoralPosition: 36
            coralArmL3CoralPosition: 36
            coralArmL4Position: 36
            coralArmUpPosition: 28
            coralArmL2AlgaePosition: 36
            coralArmL3AlgaePosition: 36
            coralArmFeederPosition: 28
            coralArmClimbPosition: 36

            coralArmMotorRotationsPerDegree: .136
    elevator:
        implemented: true
        motors:
            elevatorMotor:
                motorType: TalonFX
                motorName: elevatorMotor
                id: 16
                invertMotor: true
                currentLimit: 60
                motionMagic:
                    expoKV: 0.1
                    expoKA: 0.2
        pidConfig:
            slot0:
                kP: 1
                kI: 0
                kD: 0.02
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            elevatorFeederPosition: 0
            elevatorL1Position: 1
            elevatorL2CoralPosition: 14.2
            elevatorL3CoralPosition: 33.7
            elevatorL4Position: 63.1
            elevatorL2AlgaePosition: 14.2
            elevatorL3AlgaePosition: 33.7

            elevatorMotorRotationsPerUnit: 20
    ramp:
        implemented: false
        motors:
            rampMotor:
                motorType: SparkMax
                motorName: rampMotor
                id: 14
                invertMotor: false
                currentLimit: 20
        pidConfig:
            slot0:
                kP: 0.22
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            rampL1FeederPosition: 4
            rampL234FeederPosition: -9.31
            rampScorePosition: -1.357
            rampDislodgeCoralPosition: -15
            rampClimbPosition: -12.357


            rampMotorRotationsPerUnit: 0.136
            zeroingButtonChannel: 6
    pneumatic:
        implemented: false
        solenoids:
            pneumatic: 7 #idk wtf this is ngl
            pneumatic2: 6
        constants:
            pneumaticOn: 1.0
            pneumaticOff: 0.0
    ledmanager:
        implemented: false
        candle: 22
        constants:
            raveEnabled: 0
            raveSpeed: 0.05
            maxLevel: 200
            ledStripCount: 0
    camera:
        implemented: false
        constants:
            useMultiTargetOdometry: 0
infrastructure:
    canBusName: highSpeed
    ## Power Distribution ##
    pdId: 1
    pdIsRev: true
    ## Pneumatics Control ##
    compressorEnabled: true
    pcmIsRev: false
    pcmId: 0
    ## Pigeon ##
    pigeonId: 5
    isPigeon2: true
inputHandler: drivercentric # the default input handler
constants:
    zeroingButton: 9 # channel of DIO port
    enableMusic: 0
    ## Drivetrain ##
    minAllowablePoseError: 0.025
    maxAllowablePoseError: 5
    soundOnConfig: 0 #If this is false, It will still beep on robot bootup.
    rotationToleranceClosedLoop: 0.5
    ## Logging ##
    logRobot: 1 # 0 or 1
    logDrivetrain: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    ## General ##
    usingVision: 0
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .025 # seconds
    isProLicensed: 0
    hasCanivore: 1 # 0 or 1
    resetFactoryDefaults: 1 # whether motors get reset to factory default