subsystems:
    drivetrain:
        implemented: true
        motors:
            RRDr:
                motorType: TalonFX
                motorName: BRDr
                id: 0
                invertMotor: false
            RRAz:
                motorType: TalonFX
                motorName: BRAz
                id: 1
                invertMotor: false
            FRDr:
                motorType: TalonFX
                motorName: FRDr
                id: 3
                invertMotor: false
            FRAz:
                motorType: TalonFX
                motorName: FRAz
                id: 4
                invertMotor: false
            FLDr:
                motorType: TalonFX
                motorName: FLDr
                id: 6
                invertMotor: false
            FLAz:
                motorType: TalonFX
                motorName: FLAz
                id: 7
                invertMotor: false
            RLDr:
                motorType: TalonFX
                motorName: BLDr
                id: 9
                invertMotor: false
            RLAz:
                motorType: TalonFX
                motorName: BLAz
                id: 10
                invertMotor: false
        canCoders:
            RREnc: 2
            FREnc: 5
            FLEnc: 8
            RLEnc: 11
        swerveModules:
            modules:
                backRight:
                    drive: RRDr
                    azimuth: RRAz
                    canCoder: RREnc
                    xCoord: -11.875
                    yCoord: -11.875
                    constants:
                        encoderOffset: 0.3076171875
                        couplingRatio: 3.589
                        freeSpin12VRPS: 104
                        invertSensorPhase: 1
                frontRight:
                    drive: FRDr
                    azimuth: FRAz
                    canCoder: FREnc
                    xCoord: 11.875
                    yCoord: -11.875
                    constants:
                        encoderOffset: 0.014404296875
                        couplingRatio: 3.579
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                frontLeft:
                    drive: FLDr
                    azimuth: FLAz
                    canCoder: FLEnc
                    xCoord: 11.875
                    yCoord: 11.875
                    constants:
                        encoderOffset: 0.34228515625
                        couplingRatio: 3.576
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                backLeft:
                    drive: RLDr
                    azimuth: RLAz
                    canCoder: RLEnc
                    xCoord: -11.875
                    yCoord: 11.875
                    constants:
                        encoderOffset: 0.23779296875
                        couplingRatio: 3.572
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
            drivePID:
                slot0:
                    kP: 0.0065
                    kI: 0
                    kD: 0.00005
                    kV: 0.00925
                    kS: 0
                    kA: 0
                    kG: 0
            azimuthPID:
                slot0:
                    kP: 0.1
                    kI: 0
                    kD: 0
                    kV: 0.124
                    kS: 0
                    kA: 0
                    kG: 0
        constants:
            ## Positional Configurations ##
            openLoopRampRate: 0.1
            isSwerve: 1
            isCTRSwerve: 1 #TODO IF ALL ELSE FAILS
            ## Velocity Constraints ##
            maxRotVel: 0.8 # Pi radians/sec
            maxRotVelClosedLoop: 2 # Pi radians/sec
            wheelDiameter: 4
            trackWidth: 22.75 # inches
            wheelbaseLength: 22.75 # inches
            maxVelOpenLoop: 1 # meters/s
            maxVelPathFollowing: .3 # meters/s
            maxAccel: .1 # meters/s^2
            isDemoMode: 0
            ## Swerve Characterization ##
            azimuthEncPPR: 2048
            ## Control Configurations ##
            slowModeScalar: 0.4
            turboModeScalar: 1.73
            driveDeadband: 0.1
            rotationalDeadband: 0.1
            inputDeadband: 0.15 # Deadband of the normalized input
            snapDivisor: 30
    coralArm:
        implemented: false
        motors:
            coralArmIntakeMotor:
                motorType: SparkMax
                motorName: coralArmIntakeMotor
                id: 12
                invertMotor: false
                currentLimit: 20
            coralArmPivotMotor:
                motorType: TalonFX
                motorName: coralArmPivotMotor
                id: 13
                invertMotor: true
                currentLimit: 20
                isLowSpeedCanBus: true
                motionMagic:
                    expoKV: 0.12
                    expoKA: 0.1
        pidConfig:
            slot0: #Pivot
                kP: 0.05
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            intakeSpeed: -30
            outtakeSpeed: 30
            holdSpeed: 0

            coralSensorChannel: 0

            coralArmL1Position: 35
            coralArmL2Position: 35
            coralArmL3Position: 35
            coralArmL4Position: 35

            coralArmFeederPosition: 23

            coralArmMotorRotationsPerDegree: 1
    algaeCatcher:
        implemented: false
        motors:
            algaeCatcherIntakeMotor:
                motorType: TalonFX
                motorName: algaeCatcherIntakeMotor
                id: 14
                invertMotor: false
                currentLimit: 20
            algaeCatcherPositionMotor:
                motorType: TalonFX
                motorName: algaeCatcherPositionMotor
                id: 15
                invertMotor: true
                currentLimit: 20
                motionMagic:
                    expoKV: 0.05
                    expoKA: 0.15
        pidConfig:
            slot0: #Position
                kP: 0.8
                ki: 0
                kD: 0.02
                kV: 0
                kS: 0
                kA: 0
                kG: 0
                gravityType: cosine
        constants: # TODO: all of these
            algaeCollectSpeed: -50
            algaeHoldSpeed: 0
            algaeReleaseSpeed: 50

            algaeSensorChannel: 1

            stowPosition: 0.1
            intakePosition: 11
            holdPosition: 11
            outtakePosition: 11
            algaeL2Position: 25
            algaeL3Position: 38

            algaeMotorRotationsPerDegree: .25
    elevator:
        implemented: false
        motors:
            elevatorMotor:
                motorType: TalonFX
                motorName: elevatorMotor
                id: 16
                invertMotor: true
                currentLimit: 60
                motionMagic:
                    expoKV: 0.4
                    expoKA: 0.4
        pidConfig:
            slot0:
                kP: .8
                kI: 0
                kD: 0.02
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            elevatorRestPosition: 0
            elevatorFeederPosition: 0
            elevatorL1Position: 0
            elevatorL2Position: 7.0
            elevatorL3Position: 21.8
            elevatorL4Position: 57.2

            elevatorMotorRotationsPerUnit: 1
    pneumatic:
        implemented: true
        solenoids:
            pneumatic: 7 #idk wtf this is ngl
            pneumatic2: 6
        constants:
            pneumaticOn: 1.0
            pneumaticOff: 0.0
    camera:
        implemented: false
        constants:
            useMultiTargetOdometry: 0
infrastructure:
    canBusName: highSpeed
    ## Power Distribution ##
    pdId: 1
    pdIsRev: true
    ## Pneumatics Control ##
    compressorEnabled: true
    pcmIsRev: false
    pcmId: 0
    ## Pigeon ##
    pigeonId: 5
    isPigeon2: true
inputHandler: drivercentric # the default input handler
constants:
    zeroingButton: 9 # channel of DIO port
    enableMusic: 0
    ## Drivetrain ##
    minAllowablePoseError: 0.025
    maxAllowablePoseError: 5
    soundOnConfig: 0 #If this is false, It will still beep on robot bootup.
    rotationToleranceClosedLoop: 0.5
    ## Logging ##
    logRobot: 1 # 0 or 1
    logDrivetrain: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    ## General ##
    usingVision: 0
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .025 # seconds
    isProLicensed: 0
    hasCanivore: 1 # 0 or 1
    resetFactoryDefaults: 1 # whether motors get reset to factory default