# TODO: Will need to be updated once "REEFSCAPE" robot, Zone is present. Currently, is not accurate
subsystems:
    drivetrain:
        implemented: true
        motors:
            RRDr:
                motorType: TalonFX
                motorName: BRDr
                id: 0
                invertMotor: false
            RRAz:
                motorType: TalonFX
                motorName: BRAz
                id: 1
                invertMotor: false
            FRDr:
                motorType: TalonFX
                motorName: FRDr
                id: 3
                invertMotor: false
            FRAz:
                motorType: TalonFX
                motorName: FRAz
                id: 4
                invertMotor: false
            FLDr:
                motorType: TalonFX
                motorName: FLDr
                id: 6
                invertMotor: false
            FLAz:
                motorType: TalonFX
                motorName: FLAz
                id: 7
                invertMotor: false
            RLDr:
                motorType: TalonFX
                motorName: BLDr
                id: 9
                invertMotor: false
            RLAz:
                motorType: TalonFX
                motorName: BLAz
                id: 10
                invertMotor: false
        canCoders:
            RREnc: 2
            FREnc: 5
            FLEnc: 8
            RLEnc: 11
        constants:
            ## Positional Configurations ##
            openLoopRampRate: 0.1
            isSwerve: 1
            isCTRSwerve: 1 #TODO IF ALL ELSE FAILS
            ## Velocity Constraints ##
            maxRotVel: 0.8 # Pi radians/sec
            maxRotVelClosedLoop: 2 # Pi radians/sec
            trackWidth: 22.75 # inches
            wheelbaseLength: 22.75 # inches
            maxVelOpenLoop: 3 # meters/s
            maxVelPathFollowing: 4 # meters/s
            maxAccel: 2 # meters/s^2
            isDemoMode: 0
            ## Swerve Characterization ##
            azimuthEncPPR: 2048
            ## Control Configurations ##
            slowModeScalar: 0.4
            turboModeScalar: 1.73
            driveDeadband: 0.1
            rotationalDeadband: 0.1
            inputDeadband: 0.15 # Deadband of the normalized input
            snapDivisor: 30
    coralArm:
        implemented: false
        motors:
            coralArmIntakeMotor:
                motorType: SparkMax
                motorName: coralArmIntakeMotor
                id: 12
                invertMotor: false
            coralArmPivotMotor:
                motorType: TalonFX
                motorName: coralArmPivotMotor
                id: 13
                invertMotor: false
        pidConfig:
            slot0: #Intake
                kP: 5
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
            slot1: #Pivot
                kP: 5
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            intakeSpeed: 20
            outtakeSpeed: -20
            holdSpeed: 0

            coralSensorChannel: 0

            coralArmL1Position: 10
            coralArmL2Position: 20
            coralArmL3Position: 30
            coralArmL4Position: 40

            coralArmFeederPosition: 50
            coralArmRestPosition: 60

            coralArmMotorRotationsPerDegree: 1
    algaeCatcher:
        implemented: false
        motors:
            algaeCatcherIntakeMotor:
                motorType: TalonFX
                motorName: algaeCatcherIntakeMotor
                id: 14
                invertMotor: false
            algaeCatcherPositionMotor:
                motorType: TalonFX
                motorName: algaeCatcherPositionMotor
                id: 15
                invertMotor: false
        pidConfig:
            slot0: #Intake
                kP: 5
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
            slot1: #Position
                kP: 5
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            algaeCollectSpeed: -.75
            algaeHoldSpeed: 0
            algaeReleaseSpeed: 1

            algaeSensorChannel: 1

            stowPosition: 0.1
            intakePosition: 7.589
            holdPosition: 10.669
            outtakePosition: 10.699
            algaeL2Position: 17.082
            algaeL3Position: 29.919

            algaeMotorRotationsPerDegree: 8
    elevator:
        implemented: false
        motors:
            elevatorMotor:
                motorType: TalonFX
                motorName: elevatorMotor
                id: 16
                invertMotor: false
        pidConfig:
            slot0:
                kP: 5
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            elevatorRestPosition: 0
            elevatorFeederPosition: 1
            elevatorL1Position: 2
            elevatorL2Position: 2.5
            elevatorL3Position: 3
            elevatorL4Position: 3.5

            elevatorMotorRotationsPerUnit: 1
    pneumatic:
        implemented: false
        solenoids:
            pneumatic: -1 #idk wtf this is ngl
        constants:
            pneumaticOn: 1.0
            pneumaticOff: 0.0
    camera:
        implemented: false
        constants:
            useMultiTargetOdometry: 0
infrastructure:
    canBusName: highSpeed
    ## Power Distribution ##
    pdId: 1
    pdIsRev: true
    ## Pneumatics Control ##
    compressorEnabled: false
    pcmIsRev: false
    pcmId: -1
    ## Pigeon ##
    pigeonId: 5
    isPigeon2: true
inputHandler: drivercentric # the default input handler
constants:
    zeroingButton: 9 # channel of DIO port
    enableMusic: 0
    ## Drivetrain ##
    minAllowablePoseError: 0.025
    maxAllowablePoseError: 5
    soundOnConfig: 0 #If this is false, It will still beep on robot bootup.
    rotationToleranceClosedLoop: 0.5
    ## Logging ##
    logRobot: 1 # 0 or 1
    logDrivetrain: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    ## General ##
    usingVision: 0
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .025 # seconds
    isProLicensed: 0
    hasCanivore: 1 # 0 or 1
    resetFactoryDefaults: 1 # whether motors get reset to factory default