# TODO: Will need to be updated once "REEFSCAPE" robot, Zone is present. Currently, is not accurate
subsystems:
    drivetrain:
        implemented: true
        motors:
            RRDr:
                motorType: TalonFX
                motorName: BRDr
                id: 0
                invertMotor: false
            RRAz:
                motorType: TalonFX
                motorName: BRAz
                id: 1
                invertMotor: false
            FRDr:
                motorType: TalonFX
                motorName: FRDr
                id: 3
                invertMotor: false
            FRAz:
                motorType: TalonFX
                motorName: FRAz
                id: 4
                invertMotor: false
            FLDr:
                motorType: TalonFX
                motorName: FLDr
                id: 6
                invertMotor: false
            FLAz:
                motorType: TalonFX
                motorName: FLAz
                id: 7
                invertMotor: false
            RLDr:
                motorType: TalonFX
                motorName: BLDr
                id: 9
                invertMotor: false
            RLAz:
                motorType: TalonFX
                motorName: BLAz
                id: 10
                invertMotor: false

        canCoders:
            RREnc: 2
            FREnc: 5
            FLEnc: 8
            RLEnc: 11
        swerveModules:
            modules:
                backRight:
                    drive: RRDr
                    azimuth: RRAz
                    canCoder: RREnc
                    xCoord: -11.375
                    yCoord: -11.375
                    constants:
                        encoderOffset: 0.3076171875
                        couplingRatio: 3.589
                        freeSpin12VRPS: 104
                        invertSensorPhase: 1
                frontRight:
                    drive: FRDr
                    azimuth: FRAz
                    canCoder: FREnc
                    xCoord: 7.125
                    yCoord: -11.375
                    constants:
                        encoderOffset: 0.014404296875
                        couplingRatio: 3.579
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                frontLeft:
                    drive: FLDr
                    azimuth: FLAz
                    canCoder: FLEnc
                    xCoord: 7.125
                    yCoord: 11.375
                    constants:
                        encoderOffset: 0.34228515625
                        couplingRatio: 3.576
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
                backLeft:
                    drive: RLDr
                    azimuth: RLAz
                    canCoder: RLEnc
                    xCoord: -11.375
                    yCoord: 11.375
                    constants:
                        encoderOffset: 0.23779296875
                        couplingRatio: 3.572
                        freeSpin12VRPS: 101
                        invertSensorPhase: 1
            drivePID:
                slot0:
                    kP: 0.0065
                    kI: 0
                    kD: 0.00005
                    kV: 0.00925
                    kS: 0
                    kA: 0
                    kG: 0
            azimuthPID:
                slot0:
                    kP: 5
                    kI: 0
                    kD: 0
                    kV: 0
                    kS: 0
                    kA: 0
                    kG: 0
                    allowableError: 5
        constants:
            ## Positional Configurations ##
            openLoopRampRate: 0.1
            isSwerve: 1
            isCTRSwerve: 1 #TODO IF ALL ELSE FAILS
            wheelDiameter: -1 #inches
            kTrackScrubFactor: 1.0
            ## Velocity Constraints ##
            maxRotVel: 0.8 # Pi radians/sec
            maxRotVelClosedLoop: 2 # Pi radians/sec
            trackWidth: 22.75 # inches
            wheelbaseLength: 22.75 # inches
            maxVelOpenLoop: 3 # meters/s
            maxVel12VMPS: 5.2
            maxVelPathFollowing: 4 # meters/s
            maxAccel: 2 # meters/s^2
            isDemoMode: 0
            ## Swerve Characterization ##
            driveGearRatio: 1 # L2
            azimuthGearRatio: 1w # MK4
            azimuthEncPPR: 0
            ## Control Configurations ##
            slowModeScalar: 0.4
            turboModeScalar: 1.73
            driveDeadband: 0.1
            rotationalDeadband: 0.1
            inputDeadband: 0.15 # Deadband of the normalized input
            snapDivisor: 30
    coralArm:
        implemented: true
        motors:
            intakeMotor:
                motorType: SparkMax
                motorName: intakeMotor
                id: 12
                invertMotor: false
            pivotMotor:
                motorType: TalonFX
                motorName: pivotMotor
                id: 13
                invertMotor: false
        pidConfig:
            slot0: #Intake
                kP: 5
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
            slot1: #Pivot
                kP: 5
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            intakeSpeed: 20
            outtakeSpeed: -20
            holdSpeed: 0

            coralSensorChannel: 0

            coralArmL1Position: 10
            coralArmL2Position: 20
            coralArmL3Position: 30
            coralArmL4Position: 40

            coralArmFeederPosition: 50
            coralArmRestPosition: 60

            coralArmMotorRotationsPerDegree: 1
    algaeCatcher:
        implemented: true
        motors:
            intakeMotor:
                motorType: TalonFX
                motorName: intakeMotor
                id: 14
                invertMotor: false
            positionMotor:
                motorType: TalonFX
                motorName: positionMotor
                id: 15
                invertMotor: false
        pidConfig:
            slot0: #Intake
                kP: 5
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
            slot1: #Position
                kP: 5
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            algaeCollectSpeed: -0.5
            algaeHoldSpeed: -0.1
            algaeReleaseSpeed: 0.25

            algaeSensorChannel: 1

            stowPosition: 110
            intakePosition: 90
            holdPosition: 70
            outtakePosition: 10
            algaeL2Position: 30
            algaeL3Position: 50

            algaeMotorRotationsPerDegree: 1
    elevator:
        implemented: true
        motors:
            elevatorMotor:
                motorType: TalonFX
                motorName: elevatorMotor
                id: 16
                invertMotor: false
        pidConfig:
            slot0:
                kP: 5
                kI: 0
                kD: 0
                kV: 0
                kS: 0
                kA: 0
                kG: 0
        constants: # TODO: all of these
            elevatorRestPosition: 0
            elevatorFeederPosition: 1
            elevatorL1Position: 2
            elevatorL2Position: 2.5
            elevatorL3Position: 3
            elevatorL4Position: 3.5

            elevatorMotorRotationsPerUnit: 1
    pneumatic:
        implemented: true
        solenoids:
            pneumatic: -1 #idk wtf this is ngl
        constants:
            pneumaticOn: 1.0
            pneumaticOff: 0.0
    camera:
        implemented: false
        constants:
            useMultiTargetOdometry: 0
infrastructure:
    canBusName: highSpeed
    ## Power Distribution ##
    pdId: 1
    pdIsRev: true
    ## Pneumatics Control ##
    compressorEnabled: false
    pcmIsRev: false
    pcmId: -1
    ## Pigeon ##
    pigeonId: 5
    isPigeon2: true
inputHandler: sim # the default input handler
constants:
    zeroingButton: 9 # channel of DIO port
    enableMusic: 0
    ## Drivetrain ##
    minAllowablePoseError: 0.025
    maxAllowablePoseError: 5
    soundOnConfig: 0 #If this is false, It will still beep on robot bootup.
    rotationToleranceClosedLoop: 0.5
    ## Logging ##
    logRobot: 1 # 0 or 1
    logDrivetrain: 1 # 0 or 1
    configStatusFrames: 0 # 0 or 1
    ## General ##
    usingVision: 0
    teleopFieldCentric: 1 # 0 or 1
    kLooperDt: .025 # seconds
    isProLicensed: 0
    hasCanivore: 1 # 0 or 1
    resetFactoryDefaults: 1 # whether motors get reset to factory default